In [3]:
import pandas as pd

In [14]:
data=pd.read_csv("/home/user/Downloads/fertilizer_recommendation_unclean.csv")

In [15]:
data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,NaN,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
1,Silt,5.453217,57.352151,0.245066,0.187012,NaN,48.048418,20.642292,19.072877,44.893302,1136.185270,Maize,Vegetative,Kharif,Sprinkler??,Potato,Central,83.281750,5.342056,Urea
2,NaN,8.229938,41.595209,1.114318,2.125256,42.623678,NaN,NaN,33.504105,74.975814,954.710946,Cotton,NaN,Kharif,Rainfed,Tomato,South,131.808822,7.759146,Urea??
3,Clay,5.097788,13.897686,1.229014,0.385012,NaN,52.889805,30.488286,31.909978,54.736682,2542.438954,Wheat,Flowering,Zaid,NaN,Potato,West,230.707853,1.776405,MOP
4,NaN,7.594949,NaN,0.883794,2.061880,102.277809,50.550571,95.500318,24.750423,55.546207,792.601632,Potato??,Sowing,Kharif,Rainfed,Maize,East,194.269858,6.950905,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Silt,NaN,36.331983,0.745274,0.674293,88.398046,21.869946,71.608638,22.102699,41.274279,1682.478780,NaN,Sowing,Kharif,Drip,Sugarcane,West,49.307441,5.613273,NaN
9996,Clay,4.784560,NaN,0.928590,1.081056,39.694484,28.544436,108.290720,14.278413,35.378688,635.978518,Tomato,Harvest,Zaid,NaN,Maize,West??,82.909001,1.183053,Urea
9997,Loamy-,78.346197,40.385449,1.144741,0.982778,60.083754,69.847495,50.066041,21.761267,53.717394,447.720432,Tomato,Harvest,Rabi,Canal,Cotton,East,270.183069,1.552275,Urea
9998,Loamy,8.020147,47.152632,1.587846,0.985219,190.710502,76.849031,91.864973,326.690657,44.337344,1146.781963,Sugarcane,Vegetative,Rabi,nan-,NaN,West,233.192060,49.706247,NPK
9999,Sandy,5.727448,72.451710,1.039178,2.478555,170.543025,58.242968,32.865414,44.580646,90.247091,2785.940618,NaN,Flowering,Kharif,Canal,Cotton,South,209.126713,3.170062,MOP

In [16]:
data.duplicated().sum()

np.int64(0)

In [17]:
data.isnull().sum()

Soil_Type                      941
Soil_pH                        911
Soil_Moisture                  953
Organic_Carbon                 968
Electrical_Conductivity        943
Nitrogen_Level                 980
Phosphorus_Level               993
Potassium_Level                983
Temperature                    976
Humidity                       980
Rainfall                       945
Crop_Type                      913
Crop_Growth_Stage              980
Season                         892
Irrigation_Type                963
Previous_Crop                  963
Region                         877
Fertilizer_Used_Last_Season    996
Yield_Last_Season              953
Recommended_Fertilizer         936
dtype: int64

In [18]:
data[data['Soil_pH'].isnull()]

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,NaN,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
7,Sandy-,NaN,39.176457,0.587708,2.839372,41.727987,66.073011,24.031864,NaN,69.345882,NaN,Wheat,Harvest,Rabi,Sprinkler,Sugarcane,East,147.693026,1.697436,Urea
11,Clay,NaN,13.788126,8.456876,NaN,69.420714,70.262067,103.856447,NaN,50.473434,2325.660495,Potato,Vegetative,Rabi,Rainfed,Tomato,West,157.787691,4.718809,NPK
16,Silt,NaN,NaN,1.446322,0.796594,109.539434,NaN,42.807441,27.093173,843.262757,NaN,Rice,Sowing,Kharif,Rainfed,Cotton,North,65.842684,8.365420,DAP
25,Loamy,NaN,57.974580,0.554656,2.508896,130.919713,14.357854,81.660793,17.517796,100.440828,2360.567393,Sugarcane,Flowering,Zaid,Drip,Rice###,Central,284.829301,7.953559,DAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9963,Sandy,NaN,52.502438,1.382132,0.609401,140.519089,57.622632,NaN,12.434542,NaN,NaN,Tomato,Harvest,Zaid,Rainfed,Cotton,West,246.381912,2.238373,Compost
9966,Loamy,NaN,17.875764,1.104878,NaN,154.312349,40.496119,78.542716,9.951732,46.225088,995.318416,Tomato,Sowing,Zaid,Sprinkler###,Cotton,West,76.940015,NaN,DAP
9975,Clay,NaN,NaN,1.277145,0.376382,36.429040,NaN,61.513178,32.452675,42.820869,1058.863665,Cotton,Harvest,Kharif,Drip,Cotton,West,247.768525,1.609691,Urea
9993,Loamy,NaN,19.139848,0.590882,0.408224,169.754997,75.161449,32.656253,326.690657,52.472941,1112.896312,Tomato,Vegetative,Kharif,Rainfed??,Sugarcane,nan###,236.910299,8.122543,MOP
9995,Silt,NaN,36.331983,0.745274,0.674293,88.398046,21.869946,71.608638,22.102699,41.274279,1682.478780,NaN,Sowing,Kharif,Drip,Sugarcane,West,49.307441,5.613273,NaN

In [87]:
data['Soil_pH'].fillna(data['Soil_pH'].median(),inplace=True)

/tmp/ipykernel_4796/2605671348.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Soil_pH'].fillna(data['Soil_pH'].median(),inplace=True)

In [88]:
data['Soil_pH'].isnull().sum()

np.int64(0)

In [89]:
data['Soil_Moisture'].fillna(data['Soil_Moisture'].median(),inplace=True)

/tmp/ipykernel_4796/2110732483.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Soil_Moisture'].fillna(data['Soil_Moisture'].median(),inplace=True)

In [90]:
data['Soil_Moisture'].isnull().sum()

np.int64(0)

In [26]:
data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.511261,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
1,Silt,5.453217,57.352151,0.245066,0.187012,NaN,48.048418,20.642292,19.072877,44.893302,1136.185270,Maize,Vegetative,Kharif,Sprinkler??,Potato,Central,83.281750,5.342056,Urea
2,NaN,8.229938,41.595209,1.114318,2.125256,42.623678,NaN,NaN,33.504105,74.975814,954.710946,Cotton,NaN,Kharif,Rainfed,Tomato,South,131.808822,7.759146,Urea??
3,Clay,5.097788,13.897686,1.229014,0.385012,NaN,52.889805,30.488286,31.909978,54.736682,2542.438954,Wheat,Flowering,Zaid,NaN,Potato,West,230.707853,1.776405,MOP
4,NaN,7.594949,35.595219,0.883794,2.061880,102.277809,50.550571,95.500318,24.750423,55.546207,792.601632,Potato??,Sowing,Kharif,Rainfed,Maize,East,194.269858,6.950905,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Silt,6.511261,36.331983,0.745274,0.674293,88.398046,21.869946,71.608638,22.102699,41.274279,1682.478780,NaN,Sowing,Kharif,Drip,Sugarcane,West,49.307441,5.613273,NaN
9996,Clay,4.784560,35.595219,0.928590,1.081056,39.694484,28.544436,108.290720,14.278413,35.378688,635.978518,Tomato,Harvest,Zaid,NaN,Maize,West??,82.909001,1.183053,Urea
9997,Loamy-,78.346197,40.385449,1.144741,0.982778,60.083754,69.847495,50.066041,21.761267,53.717394,447.720432,Tomato,Harvest,Rabi,Canal,Cotton,East,270.183069,1.552275,Urea
9998,Loamy,8.020147,47.152632,1.587846,0.985219,190.710502,76.849031,91.864973,326.690657,44.337344,1146.781963,Sugarcane,Vegetative,Rabi,nan-,NaN,West,233.192060,49.706247,NPK
9999,Sandy,5.727448,72.451710,1.039178,2.478555,170.543025,58.242968,32.865414,44.580646,90.247091,2785.940618,NaN,Flowering,Kharif,Canal,Cotton,South,209.126713,3.170062,MOP

In [91]:
data['Organic_Carbon'].isnull().sum()

np.int64(0)

In [92]:
data['Organic_Carbon'].fillna(data['Organic_Carbon'].median(),inplace=True)

/tmp/ipykernel_4796/4065175796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Organic_Carbon'].fillna(data['Organic_Carbon'].median(),inplace=True)

In [93]:
data['Electrical_Conductivity'].fillna(data['Electrical_Conductivity'].median(),inplace=True)

/tmp/ipykernel_4796/952966633.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Electrical_Conductivity'].fillna(data['Electrical_Conductivity'].median(),inplace=True)

In [94]:
data['Nitrogen_Level'].fillna(data['Nitrogen_Level'].median(),inplace=True)

/tmp/ipykernel_4796/1749259578.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Nitrogen_Level'].fillna(data['Nitrogen_Level'].median(),inplace=True)

In [95]:
data['Phosphorus_Level'].fillna(data['Phosphorus_Level'].median(),inplace=True)

/tmp/ipykernel_4796/4220405255.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Phosphorus_Level'].fillna(data['Phosphorus_Level'].median(),inplace=True)

In [96]:
data['Temperature'].fillna(data['Temperature'].median(),inplace=True)

/tmp/ipykernel_4796/535127503.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Temperature'].fillna(data['Temperature'].median(),inplace=True)

In [97]:
data['Potassium_Level'].fillna(data['Potassium_Level'].median(),inplace=True)

/tmp/ipykernel_4796/2165654622.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Potassium_Level'].fillna(data['Potassium_Level'].median(),inplace=True)

In [98]:
data['Humidity'].fillna(data['Humidity'].median(),inplace=True)

/tmp/ipykernel_4796/2208946752.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Humidity'].fillna(data['Humidity'].median(),inplace=True)

In [99]:
data['Rainfall'].fillna(data['Rainfall'].median(),inplace=True)

/tmp/ipykernel_4796/3549516806.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Rainfall'].fillna(data['Rainfall'].median(),inplace=True)

In [100]:
data['Fertilizer_Used_Last_Season'].fillna(data['Fertilizer_Used_Last_Season'].median(),inplace=True)

/tmp/ipykernel_4796/2325189487.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Fertilizer_Used_Last_Season'].fillna(data['Fertilizer_Used_Last_Season'].median(),inplace=True)

In [101]:
data['Yield_Last_Season'].fillna(data['Yield_Last_Season'].median(),inplace=True)

/tmp/ipykernel_4796/3716055556.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Yield_Last_Season'].fillna(data['Yield_Last_Season'].median(),inplace=True)

In [102]:
data.isnull().sum()

Soil_Type                      0
Soil_pH                        0
Soil_Moisture                  0
Organic_Carbon                 0
Electrical_Conductivity        0
Nitrogen_Level                 0
Phosphorus_Level               0
Potassium_Level                0
Temperature                    0
Humidity                       0
Rainfall                       0
Crop_Type                      0
Crop_Growth_Stage              0
Season                         0
Irrigation_Type                0
Previous_Crop                  0
Region                         0
Fertilizer_Used_Last_Season    0
Yield_Last_Season              0
Recommended_Fertilizer         0
dtype: int64

In [39]:
data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.511261,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
1,Silt,5.453217,57.352151,0.245066,0.187012,89.232225,48.048418,20.642292,19.072877,44.893302,1136.185270,Maize,Vegetative,Kharif,Sprinkler??,Potato,Central,83.281750,5.342056,Urea
2,NaN,8.229938,41.595209,1.114318,2.125256,42.623678,48.982637,64.415963,33.504105,74.975814,954.710946,Cotton,NaN,Kharif,Rainfed,Tomato,South,131.808822,7.759146,Urea??
3,Clay,5.097788,13.897686,1.229014,0.385012,89.232225,52.889805,30.488286,31.909978,54.736682,2542.438954,Wheat,Flowering,Zaid,NaN,Potato,West,230.707853,1.776405,MOP
4,NaN,7.594949,35.595219,0.883794,2.061880,102.277809,50.550571,95.500318,24.750423,55.546207,792.601632,Potato??,Sowing,Kharif,Rainfed,Maize,East,194.269858,6.950905,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Silt,6.511261,36.331983,0.745274,0.674293,88.398046,21.869946,71.608638,22.102699,41.274279,1682.478780,NaN,Sowing,Kharif,Drip,Sugarcane,West,49.307441,5.613273,NaN
9996,Clay,4.784560,35.595219,0.928590,1.081056,39.694484,28.544436,108.290720,14.278413,35.378688,635.978518,Tomato,Harvest,Zaid,NaN,Maize,West??,82.909001,1.183053,Urea
9997,Loamy-,78.346197,40.385449,1.144741,0.982778,60.083754,69.847495,50.066041,21.761267,53.717394,447.720432,Tomato,Harvest,Rabi,Canal,Cotton,East,270.183069,1.552275,Urea
9998,Loamy,8.020147,47.152632,1.587846,0.985219,190.710502,76.849031,91.864973,326.690657,44.337344,1146.781963,Sugarcane,Vegetative,Rabi,nan-,NaN,West,233.192060,49.706247,NPK
9999,Sandy,5.727448,72.451710,1.039178,2.478555,170.543025,58.242968,32.865414,44.580646,90.247091,2785.940618,NaN,Flowering,Kharif,Canal,Cotton,South,209.126713,3.170062,MOP

In [143]:
data['Soil_Type'].fillna(data['Soil_Type'].mode()[0],inplace=True)

/tmp/ipykernel_4796/1225177325.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Soil_Type'].fillna(data['Soil_Type'].mode()[0],inplace=True)

In [41]:
data['Soil_Type'].isnull().sum()

np.int64(0)

In [142]:
data['Crop_Type'].fillna(data['Crop_Type'].mode()[0],inplace=True)

/tmp/ipykernel_4796/3293455588.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Crop_Type'].fillna(data['Crop_Type'].mode()[0],inplace=True)

In [141]:
data['Crop_Growth_Stage'].fillna(data['Crop_Growth_Stage'].mode()[0],inplace=True)

/tmp/ipykernel_4796/3029255127.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Crop_Growth_Stage'].fillna(data['Crop_Growth_Stage'].mode()[0],inplace=True)

In [140]:
data['Season'].fillna(data['Season'].mode()[0],inplace=True)

/tmp/ipykernel_4796/463054340.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Season'].fillna(data['Season'].mode()[0],inplace=True)

In [139]:
data['Irrigation_Type'].fillna(data['Irrigation_Type'].mode()[0],inplace=True)

/tmp/ipykernel_4796/3030797395.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Irrigation_Type'].fillna(data['Irrigation_Type'].mode()[0],inplace=True)

In [138]:
data['Region'].fillna(data['Region'].mode()[0],inplace=True)

/tmp/ipykernel_4796/2642425233.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Region'].fillna(data['Region'].mode()[0],inplace=True)

In [137]:
data['Previous_Crop'].fillna(data['Previous_Crop'].mode()[0],inplace=True)

/tmp/ipykernel_4796/2203613129.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Previous_Crop'].fillna(data['Previous_Crop'].mode()[0],inplace=True)

In [48]:
data.isnull().sum()

Soil_Type                        0
Soil_pH                          0
Soil_Moisture                    0
Organic_Carbon                   0
Electrical_Conductivity          0
Nitrogen_Level                   0
Phosphorus_Level                 0
Potassium_Level                  0
Temperature                      0
Humidity                         0
Rainfall                         0
Crop_Type                        0
Crop_Growth_Stage                0
Season                           0
Irrigation_Type                  0
Previous_Crop                    0
Region                           0
Fertilizer_Used_Last_Season      0
Yield_Last_Season                0
Recommended_Fertilizer         936
dtype: int64

In [136]:
data.dropna(subset=['Recommended_Fertilizer'],inplace=True)

In [111]:
data.isnull().sum()

Soil_Type                      0
Soil_pH                        0
Soil_Moisture                  0
Organic_Carbon                 0
Electrical_Conductivity        0
Nitrogen_Level                 0
Phosphorus_Level               0
Potassium_Level                0
Temperature                    0
Humidity                       0
Rainfall                       0
Crop_Type                      0
Crop_Growth_Stage              0
Season                         0
Irrigation_Type                0
Previous_Crop                  0
Region                         0
Fertilizer_Used_Last_Season    0
Yield_Last_Season              0
Recommended_Fertilizer         0
dtype: int64

In [112]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9064 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Soil_Type                    9064 non-null   object
 1   Soil_pH                      9064 non-null   float64
 2   Soil_Moisture                9064 non-null   float64
 3   Organic_Carbon               9064 non-null   float64
 4   Electrical_Conductivity      9064 non-null   float64
 5   Nitrogen_Level               9064 non-null   float64
 6   Phosphorus_Level             9064 non-null   float64
 7   Potassium_Level              9064 non-null   float64
 8   Temperature                  9064 non-null   float64
 9   Humidity                     9064 non-null   float64
 10  Rainfall                     9064 non-null   float64
 11  Crop_Type                    9064 non-null   object
 12  Crop_Growth_Stage            9064 non-null   object
 13  Season                       9064 non-null   object
 14  Irrigation_Type              9064 non-null   object
 15  Previous_Crop                9064 non-null   object
 16  Region                       9064 non-null   object
 17  Fertilizer_Used_Last_Season  9064 non-null   float64
 18  Yield_Last_Season            9064 non-null   float64
 19  Recommended_Fertilizer       9064 non-null   object
dtypes: float64(12), object(8)
memory usage: 1.5+ MB

removing special characters

In [113]:
obj_cols=data.select_dtypes(include=['object']).columns
for col in obj_cols:
    #remove special characters
    data[col]=data[col].str.replace(r'[^a-zA-Z ]','',regex=True)
    data[col]=data[col].str.strip()

In [115]:
for col in obj_cols:
    print(col,data[col].unique())

Soil_Type ['Clay' 'Silt' 'Sandy' 'Loamy' 'nan']
Crop_Type ['Cotton' 'Maize' 'Wheat' 'Rice' 'Potato' 'Sugarcane' 'Tomato' 'nan']
Crop_Growth_Stage ['Harvest' 'Vegetative' 'Flowering' 'Sowing' 'nan']
Season ['Kharif' 'Zaid' 'Rabi' 'nan']
Irrigation_Type ['Canal' 'Sprinkler' 'Rainfed' 'Drip' 'nan']
Previous_Crop ['Wheat' 'Potato' 'Tomato' 'Sugarcane' 'Cotton' 'Maize' 'Rice' 'nan']
Region ['South' 'Central' 'West' 'North' 'East' 'nan']
Recommended_Fertilizer ['MOP' 'Urea' 'Compost' 'NPK' 'DAP' 'Zinc Sulphate' 'nan' 'SSP']

In [116]:
data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.511261,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
1,Silt,5.453217,57.352151,0.245066,0.187012,89.232225,48.048418,20.642292,19.072877,44.893302,1136.185270,Maize,Vegetative,Kharif,Sprinkler,Potato,Central,83.281750,5.342056,Urea
2,Silt,8.229938,41.595209,1.114318,2.125256,42.623678,48.982637,64.415963,33.504105,74.975814,954.710946,Cotton,Harvest,Kharif,Rainfed,Tomato,South,131.808822,7.759146,Urea
3,Clay,5.097788,13.897686,1.229014,0.385012,89.232225,52.889805,30.488286,31.909978,54.736682,2542.438954,Wheat,Flowering,Zaid,Rainfed,Potato,West,230.707853,1.776405,MOP
5,Silt,78.346197,20.830018,0.247308,1.424877,67.137770,37.057955,86.342912,25.015840,55.440879,2625.059787,Wheat,Harvest,Zaid,Sprinkler,Tomato,North,68.581861,5.099028,Urea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,Silt,9.540871,12.036884,0.564536,2.350474,29.152946,62.115473,84.526640,43.192876,42.837935,2438.308733,Wheat,Harvest,Zaid,Rainfed,Rice,North,90.328224,4.380185,Urea
9996,Clay,4.784560,35.595219,0.928590,1.081056,39.694484,28.544436,108.290720,14.278413,35.378688,635.978518,Tomato,Harvest,Zaid,Rainfed,Maize,West,82.909001,1.183053,Urea
9997,Loamy,78.346197,40.385449,1.144741,0.982778,60.083754,69.847495,50.066041,21.761267,53.717394,447.720432,Tomato,Harvest,Rabi,Canal,Cotton,East,270.183069,1.552275,Urea
9998,Loamy,8.020147,47.152632,1.587846,0.985219,190.710502,76.849031,91.864973,326.690657,44.337344,1146.781963,Sugarcane,Vegetative,Rabi,nan,Maize,West,233.192060,49.706247,NPK
9999,Sandy,5.727448,72.451710,1.039178,2.478555,170.543025,58.242968,32.865414,44.580646,90.247091,2785.940618,Wheat,Flowering,Kharif,Canal,Cotton,South,209.126713,3.170062,MOP

In [117]:
data.isnull().sum()

Soil_Type                      0
Soil_pH                        0
Soil_Moisture                  0
Organic_Carbon                 0
Electrical_Conductivity        0
Nitrogen_Level                 0
Phosphorus_Level               0
Potassium_Level                0
Temperature                    0
Humidity                       0
Rainfall                       0
Crop_Type                      0
Crop_Growth_Stage              0
Season                         0
Irrigation_Type                0
Previous_Crop                  0
Region                         0
Fertilizer_Used_Last_Season    0
Yield_Last_Season              0
Recommended_Fertilizer         0
dtype: int64

In [121]:
data=pd.read_csv("/home/user/Downloads/fertilizer_recommendation.csv")

In [120]:
data.to_csv("/home/user/Downloads/fertilizer_recommendation.csv",index=False)

In [122]:
data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.511261,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
1,Silt,5.453217,57.352151,0.245066,0.187012,89.232225,48.048418,20.642292,19.072877,44.893302,1136.185270,Maize,Vegetative,Kharif,Sprinkler,Potato,Central,83.281750,5.342056,Urea
2,Silt,8.229938,41.595209,1.114318,2.125256,42.623678,48.982637,64.415963,33.504105,74.975814,954.710946,Cotton,Harvest,Kharif,Rainfed,Tomato,South,131.808822,7.759146,Urea
3,Clay,5.097788,13.897686,1.229014,0.385012,89.232225,52.889805,30.488286,31.909978,54.736682,2542.438954,Wheat,Flowering,Zaid,Rainfed,Potato,West,230.707853,1.776405,MOP
4,Silt,78.346197,20.830018,0.247308,1.424877,67.137770,37.057955,86.342912,25.015840,55.440879,2625.059787,Wheat,Harvest,Zaid,Sprinkler,Tomato,North,68.581861,5.099028,Urea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9059,Silt,9.540871,12.036884,0.564536,2.350474,29.152946,62.115473,84.526640,43.192876,42.837935,2438.308733,Wheat,Harvest,Zaid,Rainfed,Rice,North,90.328224,4.380185,Urea
9060,Clay,4.784560,35.595219,0.928590,1.081056,39.694484,28.544436,108.290720,14.278413,35.378688,635.978518,Tomato,Harvest,Zaid,Rainfed,Maize,West,82.909001,1.183053,Urea
9061,Loamy,78.346197,40.385449,1.144741,0.982778,60.083754,69.847495,50.066041,21.761267,53.717394,447.720432,Tomato,Harvest,Rabi,Canal,Cotton,East,270.183069,1.552275,Urea
9062,Loamy,8.020147,47.152632,1.587846,0.985219,190.710502,76.849031,91.864973,326.690657,44.337344,1146.781963,Sugarcane,Vegetative,Rabi,NaN,Maize,West,233.192060,49.706247,NPK
9063,Sandy,5.727448,72.451710,1.039178,2.478555,170.543025,58.242968,32.865414,44.580646,90.247091,2785.940618,Wheat,Flowering,Kharif,Canal,Cotton,South,209.126713,3.170062,MOP

In [132]:
data['Soil_Type'].unique()

array(['Clay', 'Silt', 'Sandy', 'Loamy', nan], dtype=object)

In [160]:
data['Crop_Type'].unique()

array(['Cotton', 'Maize', 'Wheat', 'Rice', 'Potato', 'Sugarcane',
       'Tomato'], dtype=object)

In [159]:
data['Crop_Growth_Stage'].unique()

array(['Harvest', 'Vegetative', 'Flowering', 'Sowing'], dtype=object)

In [158]:
data['Season'].unique()

array(['Kharif', 'Zaid', 'Rabi'], dtype=object)

In [157]:
data['Previous_Crop'].unique()

array(['Wheat', 'Potato', 'Tomato', 'Sugarcane', 'Cotton', 'Maize',
       'Rice'], dtype=object)

In [156]:
data['Region'].unique()

array(['South', 'Central', 'West', 'North', 'East'], dtype=object)

In [155]:
data['Irrigation_Type'].unique()

array(['Canal', 'Sprinkler', 'Rainfed', 'Drip'], dtype=object)

In [154]:
data['Recommended_Fertilizer'].unique()

array(['MOP', 'Urea', 'Compost', 'NPK', 'DAP', 'Zinc Sulphate', 'SSP'],
      dtype=object)

In [65]:
import numpy as np

In [128]:
data['Season'].replace('nan',np.nan)

0       Kharif
1       Kharif
2       Kharif
3         Zaid
4         Zaid
         ...
9059      Zaid
9060      Zaid
9061      Rabi
9062      Rabi
9063    Kharif
Name: Season, Length: 9064, dtype: object

In [67]:
data['Season'].replace('nan',np.nan)

0       Kharif
1       Kharif
2       Kharif
3         Zaid
5         Zaid
         ...
9994      Zaid
9996      Zaid
9997      Rabi
9998      Rabi
9999    Kharif
Name: Season, Length: 9064, dtype: object

In [153]:
data['Season'].unique()

array(['Kharif', 'Zaid', 'Rabi'], dtype=object)

In [69]:
data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.511261,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
1,Silt,5.453217,57.352151,0.245066,0.187012,89.232225,48.048418,20.642292,19.072877,44.893302,1136.185270,Maize,Vegetative,Kharif,Sprinkler,Potato,Central,83.281750,5.342056,Urea
2,Silt,8.229938,41.595209,1.114318,2.125256,42.623678,48.982637,64.415963,33.504105,74.975814,954.710946,Cotton,Harvest,Kharif,Rainfed,Tomato,South,131.808822,7.759146,Urea
3,Clay,5.097788,13.897686,1.229014,0.385012,89.232225,52.889805,30.488286,31.909978,54.736682,2542.438954,Wheat,Flowering,Zaid,Rainfed,Potato,West,230.707853,1.776405,MOP
5,Silt,78.346197,20.830018,0.247308,1.424877,67.137770,37.057955,86.342912,25.015840,55.440879,2625.059787,Wheat,Harvest,Zaid,Sprinkler,Tomato,North,68.581861,5.099028,Urea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,Silt,9.540871,12.036884,0.564536,2.350474,29.152946,62.115473,84.526640,43.192876,42.837935,2438.308733,Wheat,Harvest,Zaid,Rainfed,Rice,North,90.328224,4.380185,Urea
9996,Clay,4.784560,35.595219,0.928590,1.081056,39.694484,28.544436,108.290720,14.278413,35.378688,635.978518,Tomato,Harvest,Zaid,Rainfed,Maize,West,82.909001,1.183053,Urea
9997,Loamy,78.346197,40.385449,1.144741,0.982778,60.083754,69.847495,50.066041,21.761267,53.717394,447.720432,Tomato,Harvest,Rabi,Canal,Cotton,East,270.183069,1.552275,Urea
9998,Loamy,8.020147,47.152632,1.587846,0.985219,190.710502,76.849031,91.864973,326.690657,44.337344,1146.781963,Sugarcane,Vegetative,Rabi,nan,Maize,West,233.192060,49.706247,NPK
9999,Sandy,5.727448,72.451710,1.039178,2.478555,170.543025,58.242968,32.865414,44.580646,90.247091,2785.940618,Wheat,Flowering,Kharif,Canal,Cotton,South,209.126713,3.170062,MOP

In [70]:
data['Recommended_Fertilizer'].replace('nan',np.nan)

0        MOP
1       Urea
2       Urea
3        MOP
5       Urea
        ...
9994    Urea
9996    Urea
9997    Urea
9998     NPK
9999     MOP
Name: Recommended_Fertilizer, Length: 9064, dtype: object

In [152]:
data['Recommended_Fertilizer'].unique()

array(['MOP', 'Urea', 'Compost', 'NPK', 'DAP', 'Zinc Sulphate', 'SSP'],
      dtype=object)

In [73]:
data['Region'].replace('nan',np.nan)

0         South
1       Central
2         South
3          West
5         North
         ...
9994      North
9996       West
9997       East
9998       West
9999      South
Name: Region, Length: 9064, dtype: object

In [151]:
data['Region'].unique()

array(['South', 'Central', 'West', 'North', 'East'], dtype=object)

In [75]:
data['Previous_Crop'].replace('nan',np.nan)

0        Wheat
1       Potato
2       Tomato
3       Potato
5       Tomato
         ...
9994      Rice
9996     Maize
9997    Cotton
9998     Maize
9999    Cotton
Name: Previous_Crop, Length: 9064, dtype: object

In [150]:
data['Previous_Crop'].unique()

array(['Wheat', 'Potato', 'Tomato', 'Sugarcane', 'Cotton', 'Maize',
       'Rice'], dtype=object)

In [77]:
data['Irrigation_Type'].replace('nan',np.nan)

0           Canal
1       Sprinkler
2         Rainfed
3         Rainfed
5       Sprinkler
          ...
9994      Rainfed
9996      Rainfed
9997        Canal
9998          NaN
9999        Canal
Name: Irrigation_Type, Length: 9064, dtype: object

In [149]:
data['Irrigation_Type'].unique()

array(['Canal', 'Sprinkler', 'Rainfed', 'Drip'], dtype=object)

In [79]:
data['Crop_Growth_Stage'].replace('nan',np.nan)

0          Harvest
1       Vegetative
2          Harvest
3        Flowering
5          Harvest
           ...
9994       Harvest
9996       Harvest
9997       Harvest
9998    Vegetative
9999     Flowering
Name: Crop_Growth_Stage, Length: 9064, dtype: object

In [148]:
data['Crop_Growth_Stage'].unique()

array(['Harvest', 'Vegetative', 'Flowering', 'Sowing'], dtype=object)

In [81]:
data['Crop_Type'].replace('nan',np.nan)

0          Cotton
1           Maize
2          Cotton
3           Wheat
5           Wheat
          ...
9994        Wheat
9996       Tomato
9997       Tomato
9998    Sugarcane
9999        Wheat
Name: Crop_Type, Length: 9064, dtype: object

In [147]:
data['Crop_Type'].unique()

array(['Cotton', 'Maize', 'Wheat', 'Rice', 'Potato', 'Sugarcane',
       'Tomato'], dtype=object)

In [83]:
data['Soil_Type'].replace('nan',np.nan)

0        Clay
1        Silt
2        Silt
3        Clay
5        Silt
        ...
9994     Silt
9996     Clay
9997    Loamy
9998    Loamy
9999    Sandy
Name: Soil_Type, Length: 9064, dtype: object

In [146]:
data['Soil_Type'].unique()

array(['Clay', 'Silt', 'Sandy', 'Loamy'], dtype=object)

In [86]:
data.isnull().sum()

Soil_Type                      0
Soil_pH                        0
Soil_Moisture                  0
Organic_Carbon                 0
Electrical_Conductivity        0
Nitrogen_Level                 0
Phosphorus_Level               0
Potassium_Level                0
Temperature                    0
Humidity                       0
Rainfall                       0
Crop_Type                      0
Crop_Growth_Stage              0
Season                         0
Irrigation_Type                0
Previous_Crop                  0
Region                         0
Fertilizer_Used_Last_Season    0
Yield_Last_Season              0
Recommended_Fertilizer         0
dtype: int64

In [164]:
data.to_csv("/home/user/Downloads/fertilizer_recommendation.csv",index=False)

In [162]:

data

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Nitrogen_Level,Phosphorus_Level,Potassium_Level,Temperature,Humidity,Rainfall,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Previous_Crop,Region,Fertilizer_Used_Last_Season,Yield_Last_Season,Recommended_Fertilizer
0,Clay,6.511261,23.176586,0.335118,1.197623,61.326369,33.637166,73.198816,21.809104,100.111941,1446.742973,Cotton,Harvest,Kharif,Canal,Wheat,South,294.095892,1.083880,MOP
1,Silt,5.453217,57.352151,0.245066,0.187012,89.232225,48.048418,20.642292,19.072877,44.893302,1136.185270,Maize,Vegetative,Kharif,Sprinkler,Potato,Central,83.281750,5.342056,Urea
2,Silt,8.229938,41.595209,1.114318,2.125256,42.623678,48.982637,64.415963,33.504105,74.975814,954.710946,Cotton,Harvest,Kharif,Rainfed,Tomato,South,131.808822,7.759146,Urea
3,Clay,5.097788,13.897686,1.229014,0.385012,89.232225,52.889805,30.488286,31.909978,54.736682,2542.438954,Wheat,Flowering,Zaid,Rainfed,Potato,West,230.707853,1.776405,MOP
4,Silt,78.346197,20.830018,0.247308,1.424877,67.137770,37.057955,86.342912,25.015840,55.440879,2625.059787,Wheat,Harvest,Zaid,Sprinkler,Tomato,North,68.581861,5.099028,Urea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9059,Silt,9.540871,12.036884,0.564536,2.350474,29.152946,62.115473,84.526640,43.192876,42.837935,2438.308733,Wheat,Harvest,Zaid,Rainfed,Rice,North,90.328224,4.380185,Urea
9060,Clay,4.784560,35.595219,0.928590,1.081056,39.694484,28.544436,108.290720,14.278413,35.378688,635.978518,Tomato,Harvest,Zaid,Rainfed,Maize,West,82.909001,1.183053,Urea
9061,Loamy,78.346197,40.385449,1.144741,0.982778,60.083754,69.847495,50.066041,21.761267,53.717394,447.720432,Tomato,Harvest,Rabi,Canal,Cotton,East,270.183069,1.552275,Urea
9062,Loamy,8.020147,47.152632,1.587846,0.985219,190.710502,76.849031,91.864973,326.690657,44.337344,1146.781963,Sugarcane,Vegetative,Rabi,Rainfed,Maize,West,233.192060,49.706247,NPK
9063,Sandy,5.727448,72.451710,1.039178,2.478555,170.543025,58.242968,32.865414,44.580646,90.247091,2785.940618,Wheat,Flowering,Kharif,Canal,Cotton,South,209.126713,3.170062,MOP

In [144]:
data.isnull().sum()

Soil_Type                      0
Soil_pH                        0
Soil_Moisture                  0
Organic_Carbon                 0
Electrical_Conductivity        0
Nitrogen_Level                 0
Phosphorus_Level               0
Potassium_Level                0
Temperature                    0
Humidity                       0
Rainfall                       0
Crop_Type                      0
Crop_Growth_Stage              0
Season                         0
Irrigation_Type                0
Previous_Crop                  0
Region                         0
Fertilizer_Used_Last_Season    0
Yield_Last_Season              0
Recommended_Fertilizer         0
dtype: int64